# Generated by Django 4.0.5 on 2022-06-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandawards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
