# Generated by Django 4.0.5 on 2022-06-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandawards', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
